[tool.poetry]
name = "csvtoexcel"
version = "0.1.0"
description = ""
authors = ["司芳源 <sify21@163.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
openpyxl = "^3.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
